#!/bin/bash

mkdir -p "$HOME/daily"
cd "$HOME/daily"

# Create a log for today.
today=$(TZ="EST" date +"%Y-%m-%d")
touch "$today"

# Find the latest log prior to today.
last=$(ls | tail -2 | head -1)

vim -o "$today" "$last"
